name: Nalu-Configuration
options:
  xcodeVersion: "13.1"
  createIntermediateGroups: true
  tabWidth: 4
  minimumXcodeGenVersion: "2.24.0"
  deploymentTarget:
    iOS: "15.0"
settings:
  base:
    SDKROOT: iphoneos
    CURRENT_PROJECT_VERSION: 1
    MARKETING_VERSION: 1.0.1
    SWIFT_VERSION: 5.5
    CODE_SIGN_STYLE: Manual
    DEVELOPMENT_TEAM: AJPM5QDVLY
    OTHER_LDFLAGS: $(inherited) -ObjC
    OTHER_SWIFT_FLAGS: $(inherited)
    GENERATE_INFOPLIST_FILE: YES
    CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED: YES
    DEBUG_INFORMATION_FORMAT: "dwarf-with-dsym"
    BUILD_LIBRARY_FOR_DISTRIBUTION: YES
  configs:
    Debug:
      CODE_SIGN_IDENTITY: "Apple Developer"
      ENABLE_BITCODE: NO
      ONLY_ACTIVE_ARCH: YES
      ENABLE_TESTABILITY: YES
      GCC_SYMBOLS_PRIVATE_EXTERN: NO
      ASSETCATALOG_COMPILER_OPTIMIZATION: "time"
    Release:
      CODE_SIGN_IDENTITY: "Apple Distribution"
      ENABLE_BITCODE: YES
      SWIFT_OPTIMIZATION_LEVEL: "-Osize"
      SWIFT_COMPILATION_MODE: "wholemodule"
      ASSETCATALOG_COMPILER_OPTIMIZATION: "space"
