targets:
  TrackRoute:
    type: application
    platform: iOS
    sources: Sources
    dependencies:
      - target: Components
      - target: Data
      - target: Domain
      - target: Presentation
      - target: Networking
      - framework: ../Frameworks/DependencyInjection.xcframework
    settings:
      base:
        BUILD_LIBRARY_FOR_DISTRIBUTION: NO
        PRODUCT_BUNDLE_IDENTIFIER: "com.mobile.trackRoute"
        OTHER_LDFLAGS: $(inherited) -ObjC
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      configs:
        Debug:
          CODE_SIGN_IDENTITY: iPhone Developer
          PROVISIONING_PROFILE_SPECIFIER: "TrackRoute iOS Development"
        Release:
          CODE_SIGN_IDENTITY: iPhone Distribution
          PROVISIONING_PROFILE_SPECIFIER: "TrackRoute iOS AppStore"
    scheme:
      testTargets:
        - TrackRouteTests
  TrackRouteTests:
    type: bundle.unit-test
    platform: iOS
    sources: ./Tests
    dependencies:
      - target: ComponentsTests
      - target: DataTests
      - target: DomainTests
      - target: PresentationTests
